// Which admin boundary set the map draws and attributes cells to — shared like
// topoProfile.svelte.js: a module-level $state with getter/setter, no prop
// drilling. The DevHud cycles it. Resets to the default on every page load.
//
// Natural Earth 110m, which the map has always used, is first-order countries
// only. It has no territories at all: the entire Lesser Antilles is absent, so
// the Caribbean draws as open water with no country lines, and none of those
// places can be selected. These sets are the alternatives, so the trade can be
// judged on screen rather than argued about.
//
// The trade is the country table. Each land cell carries one index into it
// (countries.bin), and that index is a single byte — so a set is free until its
// table passes 256 entries, at which point the blob doubles in width. 50m is
// the one that buys the territories and still fits:
//
//   110m   175 entries, uint8   171 countries with cells   (what the map has always drawn)
//   50m    243 entries, uint8   204 countries with cells   (+ every dependency)
//
// 10m and 10m-units were measured too — 258 and 298 entries, so both would
// widen every profile's blob to uint16, 10m for the sake of three entries. They
// stay buildable from processing/country_sets.py for comparison but are not
// offered here and not committed; see processing/README.md.
//
// Generated by processing/2c_generate_country_sets.py (the .bin and the table)
// and 5_smooth_boundaries.py (the overlay geometry). Both ship.
export const COUNTRY_SETS = ['110m', '50m'];

// The map's long-standing default, kept as the default here so the committed
// build renders exactly as it did before this became switchable. Also the
// fallback whenever a profile has no country-sets.json.
export const DEFAULT_COUNTRY_SET = '110m';

// Enough to label the DevHud before country-sets.json has loaded. The
// authoritative table size and bit width come from that file at runtime —
// these are only for the button and its tooltip.
export const COUNTRY_SET_INFO = {
  '110m': { label: 'NE 110m countries', table: 175, bits: 8, note: 'no territories' },
  '50m': { label: 'NE 50m countries', table: 243, bits: 8, note: '+ dependencies' }
};

export function countrySetLabel(key) {
  const s = COUNTRY_SET_INFO[key];
  return s ? `${s.label} — ${s.table} entries, uint${s.bits} (${s.note})` : key;
}

// The boundary overlay for a set. Both files sit under the same naming, which
// is why this is one expression rather than a special case.
export function boundaryUrl(base, key) {
  return `${base}topojson/admin-boundaries/countries-${key}.topojson`;
}

let current = $state(DEFAULT_COUNTRY_SET);

export function countrySet() {
  return current;
}

export function setCountrySet(next) {
  if (COUNTRY_SETS.includes(next)) current = next;
}

export function cycleCountrySet() {
  const i = COUNTRY_SETS.indexOf(current);
  current = COUNTRY_SETS[(i + 1) % COUNTRY_SETS.length];
}
