// Map tile resolution, pinned for the exhibition build.
//
// The resolution used to be switchable at runtime (a dev-HUD cycle and a
// settings-panel picker over ['100km','75km','70km','60km','50km']). Both of
// those surfaces are gone here, so the value is a constant — named rather than
// sprinkled as a literal, since it appears in the grid fetch, the map draw and
// the ring's country distribution and all three must agree.
//
// 70km is the exhibition resolution. 60km is visibly finer, but it is 58,604
// land cells against 70km's 43,598 — a 34% jump in the per-frame cost of
// projecting and filling every cell, and that is enough to take the interaction
// below comfortable.
//
// This is a GRID profile (see lib/gridSource.js): the whole 76-year series
// ships as one blob, so switching years costs no network at all. It lives in
// public/grid/ (Git LFS), which is why the per-year TopoJSON path in
// MapCanvas.loadYearData never fires — see the note there.
export const MAP_PROFILE = '70km';

// Which admin boundary set the map draws and attributes cells to.
//
// This was switchable on dev (a DevHud cycle over ['110m','50m']); like the
// resolution above, the surface is gone here and the value is a constant. It
// appears in the grid fetch, the tile-cache key and the boundary overlay URL,
// and all three must agree — a cell's country code is an index into the set's
// own table, so a mismatch mis-names every cell.
//
// 50m is the exhibition set. Natural Earth 110m, which the map used to draw, is
// first-order countries only: it has no territories at all, so the entire
// Lesser Antilles is absent, the Caribbean draws as open water with no country
// lines, and none of those places can be selected. 50m buys every dependency
// and still fits in a byte per cell, so the grid blob does not widen:
//
//   110m   175 entries, uint8   171 countries with cells
//   50m    243 entries, uint8   204 countries with cells   (+ every dependency)
//
// Generated by processing/2c_generate_country_sets.py (countries-50m.bin and
// the table in country-sets.json) and 5_smooth_boundaries.py (the overlay
// geometry). Both ship in public/ — see processing/README.md.
export const COUNTRY_SET = '50m';

// The boundary overlay for a set. Both files sit under the same naming, which
// is why this is one expression rather than a special case.
export function boundaryUrl(base, key) {
  return `${base}topojson/admin-boundaries/countries-${key}.topojson`;
}
